spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  application:
    name: pdf-analyzer
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  http:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  ai:
    model:
      embedding: ollama
      chat: ollama
    ollama:
      #base-url: "http://localhost:7777/ollama" #if using Spring Cloud Gateway
      init:
        pull-model-strategy: always
        embedding:
          additional-models:
            - nomic-embed-text:latest
            
        chat:
          additional-models:
           - hf.co/Qwen/Qwen3-30B-A3B-GGUF:A3B-Q6_K
      chat:
        options:
          model: hf.co/Qwen/Qwen3-30B-A3B-GGUF:A3B-Q6_K
          num-ctx: 131027
      embedding:
        options:
          model: nomic-embed-text:latest
    openai:
      base-url: http://localhost:11434
      model: qwen3:30b-a3b-q8_0
      api-key: ${OPENAI_API_KEY}
    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: {VECTOR_DIMENSIONS:768}
        batching-strategy: TOKEN_COUNT
        max-document-batch-size: 10000
  sql:
    init:
      mode: always
server:
  tomcat:
    max-post-size: 52428800
    max-http-header-size: 65536
    max-swallow-size: 100MB

logging:
  level:
    org:
      apache:
        pdfbox:
          pgmodel:
            font:
              FileSystemFontProvider: ERROR

app:
  ai:
    topk: 30
    maxChatHistory: 3
    beChatty: "no"
    promptTemplate: |
      <query>
      Context information is below:
      ---------------------
      <question_answer_context>
      ---------------------
      Answer the user’s question directly, using the context above.
      You may include additional general information, however you are required to clarify to the user when doing so.
    systemText: |
      You are a friendly, helpful assistant that manages a document archive. 
      Avoid meta‑phrases like "Based on the context…".
